version: '3.8'

services:
  pixiv_api_service:
    image: lun1ry/pixiv_search_api
    container_name: pixiv-search-api
    ports:
      - "2494:2494"
    environment:
      - PIXIV_REFRESH_TOKEN=${PIXIV_REFRESH_TOKEN}
    # Если вы хотите использовать .env файл для PIXIV_REFRESH_TOKEN:
    # env_file:
    #   - .env
    restart: unless-stopped 