version: '3.8'

services:
  pixiv_api_service:
    image: lun1ry/pixiv-search-api
    container_name: pixiv-search-api
    ports:
      - "2494:2494"
    environment:
      - PIXIV_REFRESH_TOKEN=${PIXIV_REFRESH_TOKEN}
    restart: unless-stopped 